name: 'Build publish and deploy'
description: 'Build project, publish to registry and deploy into the cluster'
inputs:
  workspace:
    description: 'Workspace used by terraform'
    required: true
    default: 'alpha'
  cloud-path:
    required: true
    description: "Cloud application path"
  prefix-tag:
    required: false
    description: "Prefixed used in alpha for the tag image"
    default: ""
  gcp-credentials:
    required: true
    description: "GCP services account credentials"

runs:
  using: "composite"
  steps:
    - name: Get tag
      shell: bash
      id: get_tag
      run: echo ::set-output name=TAG::$PREFIX_TAG$(echo $GITHUB_REF | cut -d / -f 3)
      env:
        PREFIX_TAG: ${{ inputs.prefix-tag }}

    - name: Terraform init and fmt
      shell: bash
      working-directory: ${{ inputs.cloud-path }}
      run: |
        terraform init
        terraform workspace select ${{ inputs.workspace }}
        terraform fmt
      env:
        GOOGLE_CREDENTIALS: ${{ inputs.gcp-credentials }}

    - name: Terraform apply
      shell: bash
      working-directory: ${{ inputs.cloud-path }}
      run: |
        terraform apply -auto-approve \
        --var app_version=$TAG \
        --var hash_id=$SHA
      env:
        TAG: ${{ steps.get_tag.outputs.TAG }}
        SHA: ${{ github.sha }}
        GOOGLE_CREDENTIALS: ${{ inputs.gcp-credentials }}
