'1.7':
  en: 'user-documentation-en'
  fr: 'user-documentation-fr'
  it: 'user-documentation-it'
  es: 'user-documentation-es'
'8.0':
  en: 'user-documentation-v8-en'
  fr: 'user-documentation-v8-fr'
