name: CONTEXTUAL HELP API INTEGRATION CD

on:
  pull_request:
    types: [opened,edited,reopened,synchronize,labeled]

env:
  GCP_PROJECT: 'core-oss-integration'
  TF_VERSION: '0.14.7'
  LABELS: ${{toJSON(github.event.pull_request.labels)}}

jobs:
  contextual_help_api_integration:
    name: Contextual Help API Integration CD
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: contains(github.event.pull_request.labels.*.name, 'integration-deployment')

    env:
      APP_PATH: '.'
      APP_CLOUD_PATH: '.cloud/'
      APP_NAME: 'help-api'

    steps:
      - name: Setting up terraform for later 🌎
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Checkout the repository 🎁
        uses: actions/checkout@v1

      - name: Set up Cloud SDK ⚙️
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ env.GCP_PROJECT }}
          service_account_key: ${{ secrets.INTEGRATION_GOOGLE_APPLICATION_CREDENTIALS }}
          export_default_credentials: true

      - name: Building API Image 👷
        uses: ./.github/actions/build
        with:
          app-path: ${{ env.APP_PATH }}
          app-name: ${{ env.APP_NAME }}
          gcp-credentials: ${{ secrets.INTEGRATION_GOOGLE_APPLICATION_CREDENTIALS }}
          gcp-project: ${{ env.GCP_PROJECT }}

#      - name: Deploying API 🚚
#        uses: ./.github/actions/deploy
#        with:
#          workspace: ${{ steps.get_bulle.outputs.BULLE }}
#          cloud-path: ${{ env.APP_CLOUD_PATH }}
#          gcp-credentials: ${{ secrets.INTEGRATION_GOOGLE_APPLICATION_CREDENTIALS }}
#          gcp-project: ${{ env.GCLOUD_NAMESPACE_INTEGRATION }}
