name: CONTEXTUAL HELP API PREPRODUCTION CD

on:
  push:
    branches:
      - main

env:
  GCP_PROJECT: 'core-oss-preproduction'
  TF_VERSION: '0.14.7'
  LABELS: ${{toJSON(github.event.pull_request.labels)}}

jobs:
  contextual_help_api_integration:
    name: Contextual Help API Preproduction CD
    runs-on: ubuntu-latest
    timeout-minutes: 15

    env:
      APP_PATH: '.'
      APP_CLOUD_PATH: '.cloud/'
      APP_NAME: 'contextual-help-api'

    steps:
      - name: Setting up terraform for later 🌎
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Checkout the repository 🎁
        uses: actions/checkout@v1

      - name: Set up Cloud SDK ⚙️
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ env.GCP_PROJECT }}
          service_account_key: ${{ secrets.PREPRODUCTION_GOOGLE_APPLICATION_CREDENTIALS }}
          export_default_credentials: true

      - name: Building Contextual Help API Image 👷
        uses: ./.github/actions/build
        with:
          app-path: ${{ env.APP_PATH }}
          app-name: ${{ env.APP_NAME }}
          gcp-credentials: ${{ secrets.PREPRODUCTION_GOOGLE_APPLICATION_CREDENTIALS }}
          gcp-project: ${{ env.GCP_PROJECT }}

      - name: Deploying Contextual Help API Image 🚚
        uses: ./.github/actions/deploy
        with:
          workspace: "preprod"
          cloud-path: ${{ env.APP_CLOUD_PATH }}
          gcp-credentials: ${{ secrets.PREPRODUCTION_GOOGLE_APPLICATION_CREDENTIALS }}
          gcp-project: ${{ env.GCP_PROJECT }}
